config/routes.rb
Rails.application.routes.draw do
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'   
 end
  root "homes#index"
  match 'questions/filter_form' => 'questions#question_filter_form', as: :question_filter_form, via: [:get, :post]
  get 'add_new_fields', to: 'questions#add_new_fields'
  get 'questions/print_page', to: 'questions#print_page', as: :question_print_page
end

app/models/ability.rb
class Ability
  include CanCan::Ability
    def initialize(user)
      user ||= User.new #guest user
    if user.type == "Admin"
      can :manage, :all
    end
    if user.type == "Editor"
      can :manage, Question
      can :manage, Technology
      can :read, [Editor]
      can [:update, :read], Editor, id: user.id
    end
    if user.type == "Viewer"
      can :read, Question
      can [:update, :read], Viewer, id: user.id
    end
  end
end

app/models/admin.rb
class Admin < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/editor.rb
class Editor < User
end

app/models/question.rb
class Question < ApplicationRecord
  validates :question, :uniqueness => true
  validates :question, :answer, :technology_id, :marks, presence: true
  belongs_to :technology
  def approve!
    update(status: true)
end
end
 

app/models/technology.rb
class Technology < ApplicationRecord
    validates :name, :uniqueness => true
    has_many :questions
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, :email, presence: true
  validates :password, :password_confirmation, presence: true, on: :create
  validates :password, confirmation: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :validatable
    # roles
    def admin?
      type == 'Admin'
    end
    def viewer?
      type == 'Viewer'
    end
    def editor?
      type == 'Editor'
    end 
  end

app/models/viewer.rb
class Viewer < User
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:new, :create]
  protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?
    protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :type, :email, :password, :password_confirmation)}
      devise_parameter_sanitizer.permit(:account_update, keys: [:username, :email])
    end
    def after_sign_in_path_for(resource)
      resource.admin? ? admin_admins_path : admin_questions_path
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def question_filter_form
    $technologies = Technology.all
    @question = params[:questions]
  end
  def add_new_fields
    respond_to do |format|
        format.html {}
        format.js
    end
  end
  def question_print_page
    respond_to do |format|
        format.html {}
        format.js
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  protected
      def update_resource(resource, params)
      # Require current password if user is trying to change password.
      return super if params["password"]&.present?
      # Allows user to update registration information without password.
      resource.update_without_password(params.except("current_password"))
    end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/homes/_navbar.html.erb
<% if user_signed_in? %>
 <span class="nav-item float-end m-5 mt-2">
    <%= link_to 'logout', destroy_user_session_path%>
  </span>
<% else %>
  <span class="nav-item float-end m-5 mt-2">
    <%= link_to 'Sign in', new_user_session_path, class: "nav-link"%>
  </span>
<% end %>

app/views/homes/index.html.erb
<%= render partial: 'navbar' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuestionAnswers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success" id="flash"><%= notice %></p>
    <% end %>
    <% if alert %>
        <p class="alert alert-danger" id="flash"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/questions/_attr_form.html.erb
<div  id="add_new_fields">
    <div class="text-end mb-3" >
        <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 30 30">
            <g id="Icon_feather-minus-circle" data-name="Icon feather-minus-circle" transform="translate(-3 -3)">
              <path id="Path_1" data-name="Path 1" d="M33,18A15,15,0,1,1,18,3,15,15,0,0,1,33,18Z" fill="#f53b3b"/>
              <path id="Path_2" data-name="Path 2" d="M12,18H24" fill="#fff" stroke="#fff" stroke-linecap="round" stroke-linejoin="round" stroke-width="3"/>
            </g>
            <%= link_to "Click To Remove", "", class: "remove-fields"%>
          </svg>
        </div>
        <div class="form-group d-flex gap-3 mb-3">
            
            <%= select_tag 'questions[][tech_id]', options_for_select($technologies.collect{ |u| [u.name, u.id] }), class: "form-select p-3", :include_blank => false, :prompt => 'Select Technology'%>
            <%= text_field_tag 'questions[][range]', nil, required: true, class: "form-select p-3", placeholder: 'How many questions?'%>
        </div>
    </div>

app/views/questions/add_new_fields.js.erb
$('#add_new_fields').append("<%= escape_javascript render('attr_form') %>");

 $('form').on('click', '#Icon_feather-minus-circle', function(event){ console.log('remove'); $(this).prev('input[type=hidden]').val('1'); $(this).closest('#add_new_fields').hide(); return event.preventDefault();

});

app/views/questions/print_page.html.erb
<!DOCTYPE html>
<html lang="en">
<div class="container">
<body>  
<h4 style="text-align: center;">INTERVIEW TEST</h4>
<h5>To be filled by candidate:</h5>
<table class="table table-bordered">
    <tr>
        <td colspan="2">Candidate Name: </td>
        <td colspan="2">Applied For: </td>
    </tr>
    <tr>
        <td colspan="2">Current Company: </td>
        <td colspan="2">Current Salary: </td>
    </tr>
    <tr>
        <td colspan="2">Expected Salary: </td>
        <td colspan="2">Expected Joining Date: </td>
    </tr>
    <tr>
        <td colspan="3"><h5>For office use only:</h5></td>
    </tr>
    <tr>
        <td colspan="2">Test Start & End Time: </td>
        <td colspan="2">Test Checked By: </td>
    </tr>
    <tr>
    <% if params[:questions].present?%>
        <% params[:questions].each do |question|%>
            <% if question[:tech_id].present? && question[:range].present? && params[:marks_range_to].present? && params[:marks_range_from].present?%>
            <% questions = Question.where(technology_id: question[:tech_id]).where(marks: params[:marks_range_from]..params[:marks_range_to]).where(status: true).limit(question[:range]).order('RAND()') %>
                <% questions.group_by{|q| q.technology_id}.each do |a|%>
                    <% tech = a[0]%>
                    <%tec = Technology.where(id: tech)%>
                    <%tec.each do |te|%>
                <td class="spacing">
                    <%= te.name%>
                <%end%>   
               <span>/<%= a[1].sum(&:marks)%></span>
                </td>

                <%end%>
        <%end%>
        <%end%>
    <%end%>
    </tr>
    <tr>
        <td colspan="6">
            <table class="table table-bordered">
                <tr>
                   <td>Remarks</td>
                </tr>
                <tr>
                    <td></td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                </tr>
            </table>
        </td>
    </tr>
</table>
<% if params[:questions].present?%>
<table class="table table-borderless m-0">
    <% params[:questions].each do |question|%>
        <% if question[:tech_id].present? && question[:range].present? && params[:marks_range_to].present? && params[:marks_range_from].present?%>
            <% questions = Question.where(technology_id: question[:tech_id]).where(marks: params[:marks_range_from]..params[:marks_range_to]).where(status: true).limit(question[:range]).order('RAND()') %>
                <tr { style = "border-bottom: 0.2rem solid black;" }>
                        <%tech = question[:tech_id]%>
                        <% @query1 = Technology.where(id: tech)%>
                        <% @query1.each do |f| %>
                        <th><%= f.name%></th>
                        <%end%>
                <tr>
            <% questions.each do |q| %>
                <tr>
                    <td>
                        QID<%= q.id%>:
                        <td><%= ques = q.question.html_safe%>
                        <%ques.capitalize%>
                        <%ques.tr(',',' ')%>
                        </td>
                    </td>
                    <td>(<%= q.marks.to_i%>)</td>
                    
                </tr>
            <% end %>
        <% end %> 
    <%end%>
</table>
<%end%>
</body>
</div>
</html>
    

app/views/questions/question_filter_form.html.erb
<div class="container p-3">
    <h1 class="text-center">Select Questions<h1>
    <div class="d-flex justify-content-between mb-3">
        <h4>Select technology</h4>
    </div>
    <%= form_tag question_print_page_path , :method => :get do |f| %>
    <div  id="add_new_fields">
        <div class="form-group d-flex gap-3 mb-3">     
            <%= select_tag 'questions[][tech_id]', options_for_select($technologies.collect{ |u| [u.name, u.id] }), class: "form-select p-3", :include_blank => false, :prompt => 'Select Technology'%>
             <%= select_tag 'questions[][range]', options_for_select([1,2,3,4,5]), class: "form-select p-3", :include_blank => false, :prompt => 'How many questions?'%>
        </div>
    </div>
        <div class="d-flex justify-content-end align-items-center gap-2">
            <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" viewBox="0 0 28 28">
                <path id="Icon_ionic-ios-add-circle" data-name="Icon ionic-ios-add-circle" d="M17.375,3.375a14,14,0,1,0,14,14A14,14,0,0,0,17.375,3.375Zm6.091,15.077H18.452v5.014a1.077,1.077,0,0,1-2.154,0V18.452H11.284a1.077,1.077,0,1,1,0-2.154H16.3V11.284a1.077,1.077,0,1,1,2.154,0V16.3h5.014a1.077,1.077,0,1,1,0,2.154Z" transform="translate(-3.375 -3.375)" fill="#3a3ffe"/>
              </svg>
              <%= link_to "Add More Technology", add_new_fields_path, remote: true, class: "link-primary text-decoration-none fs-5"%>
        </div>
        <div class="">
            <h4>Select marks range</h4>
            <div class="d-flex gap-3 mb-3">
                <%= text_field_tag 'marks_range_from', value=2, placeholder: 'From', class: "form-select p-3"%>
                  <%= text_field_tag 'marks_range_to', value=5, placeholder: 'To', class: "form-select p-3"%>
            </div>
             <%= submit_tag 'Filter', class: "btn btn-success py-2 px-4 float-end"%>
        </div>
       
        <%end%>
</div>